import { observer } from 'mobx-react-lite';
import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage
} from 'next';
import Head from 'next/head';
import React, { useEffect } from 'react';
import { ITodo } from '../src/feature/todo/ITodo';
import todoStore from '../src/feature/todo/TodoStore';
import { fetchTodo } from '../src/services/todoServices';

export const getServerSideProps: GetServerSideProps<{
  listTodo: ITodo[];
}> = async () => {
  const result = await fetchTodo();
  todoStore.setListTodo(result);
  return {
    props: {
      listTodo: todoStore.listTodo
    }
  };
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ listTodo }) => {
  return (
    <div>
      <Head>
        <title>NextJS: State menegement with Mobx </title>
        <meta
          name="description"
          content=" Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main
        className="flex min-h-screen w-full flex-col items-center justify-center border-2 font-inter text-2xl font-semibold transition-all hover:border"
        spellCheck={true}
      >
        NextJs + State management. ⚡
        <hr />
        <div className="mt-5  font-roboto text-sm">
          <ul className="flex flex-col gap-3">
            {todoStore.getTodoList.map((todo) => (
              <li key={todo.id}>
                <button
                  className="text-md p mr-2 bg-blue-600 px-2 py-1 text-white"
                  onClick={() => todoStore.onDeleteThisItem(todo.id)}
                >
                  &#xd7;
                </button>
                <strong>{todo.id}</strong> {todo.title}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  );
};

export default observer(Home);
